# Generated by Django 5.0.6 on 2025-09-14 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input1', models.CharField(max_length=100)),
                ('input2', models.CharField(max_length=100)),
                ('input3', models.CharField(max_length=100)),
                ('input4', models.CharField(max_length=100)),
                ('input5', models.CharField(max_length=100)),
                ('input6', models.CharField(max_length=100)),
                ('input7', models.CharField(max_length=100)),
                ('input8', models.CharField(max_length=100)),
                ('input9', models.CharField(max_length=100)),
                ('input10', models.CharField(max_length=100)),
                ('result', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_page1', models.BooleanField(default=False)),
                ('can_access_page2', models.BooleanField(default=False)),
                ('can_access_page3', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
