# Generated by Django 5.0.6 on 2025-09-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMachines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpagepermission',
            name='can_access_page9',
            field=models.BooleanField(default=False),
        ),
    ]
